pkg_name=effortless_audit_example
pkg_version=0.1.1
pkg_origin=collinmcneese
pkg_maintainer="Collin McNeese <collin@mydevsandbox.com>"
pkg_license=("Apache-2.0")
pkg_description="Effortless Audit Example for Linux"
pkg_scaffolding="chef/scaffolding-chef-inspec"
# pkg_scaffolding="chef/scaffolding-chef-inspec/0.24.0/20211119164421"
# scaffold_inspec_client="chef/chef-infra-client"
scaffold_profiles=(profile1 profile2)
